### ISSUE TITLE
Can we use the following command to enable the port hopping feature?

### ISSUE THREAD

**Issue by egg1234** [SenseUnit/dtlspipe#18]
Can we use the following command to enable the port hopping feature?

dtlspipe -psk xxxxxxxxxxxx server 0.0.0.0:2815-2900 127.0.0.1:514

dtlspipe -psk xxxxxxxxxxxx client 127.0.0.1:2816 203.0.113.11:2815-2900

Thank you very much!

**Comment by Snawoot** [comment]
Hi!

No, for a number of reasons. On server side you're better off with DNAT rule in iptables, on client side it's a separate command because its syntax is very different.
