### ISSUE TITLE
Can you change the header for DPI

### ISSUE THREAD

**Issue by evangelme** [SenseUnit/dtlspipe#24]
can you change the header so isp and DPI can not detect it is a dtls protocol add a fix header to it so they can not detect it if you do this i reallly really thank you. but all in all tnx for your great work.

**Comment by Snawoot** [comment]
Hello!

This application is specifically made for DTLS protocol and will continue being like that. That means packet format will be nothing different from DTLS. If you experience an issue with DTLS filtration, try to experiment with different values for `-curves` and `-ciphers` or try some another protocol and another application.
