### ISSUE TITLE
Secondary IP problem

### ISSUE THREAD

**Issue by evangelme** [SenseUnit/dtlspipe#25]
i have 2 IPs for a server imagine my IPs are 1.1.1.1 and 2.2.2.2 
i want the client to connect to 2.2.2.2:2815 and the server gives the data to client with 1.1.1.1:2815 but the tunnel gives me error because the sender and reviser's IP is not the same. how do you think i should solve this problem. i know it is not the right way to use it but our internet in on censorship and the only way i can use it permanently is this what do you suggest i should do for your DTLS tunnel to accept this connection.
Thank you.

**Comment by Snawoot** [comment]
Hi!

Each individual DTLS session can use only one IP-port pair. I believe what you want is to have DTLS session using one IP and originate IP traffic via wireguard using another IP. It's possible, just adjust SNAT rules in iptables to use second IP instead of first IP address or MASQUERADE.

**Comment by evangelme** [comment]
Hi @Snawoot,

Thank you for your reply.

I understand that you suggested using SNAT or MASQUERADE rules in iptables. However, my issue is specifically with the DTLS tunnel not accepting connections where the sender IP and receiver IP are different.

In my country, when we use VPNs or protocols like DTLS, the TX IP address gets banned after some days due to censorship. To circumvent this, I need the client to connect to one IP (2.2.2.2:2815) and have the server respond with a different IP (1.1.1.1:2815). This allows me to bypass the DPI (Deep Packet Inspection) systems that monitor and ban these connections.

Is there a way to configure the DTLS tunnel to accept this setup, where the client and server communicate using different IP addresses? I need the tunnel to handle two IPs without dropping the connection. Your guidance on this matter would be greatly appreciated.

I tried everything this is the only way if you help me with this it means a world to me.

Thank you.

**Comment by Snawoot** [comment]
> Is there a way to configure the DTLS tunnel to accept this setup

dtlspipe doesn't support that. It is possible to adjust transport to reply downstream from another IP address, but it will require support on client side as well and it won't work for majority of clients behind NAT (e.g. Port Restricted Cone or Symmetric).

For your case I'd rather suggest to try a wrapper which pretends to be a TLS transport, but still carries UDP datagrams: https://github.com/ameshkov/udptlspipe

Or consider other protocols, depends what you're trying to achieve in the end.

**Comment by evangelme** [comment]
@Snawoot  First thank you for your response and your time.
i ran Wireguard over TLS before it is good but DTLS is something else in terms of performance but thank you i do it with TLS.
