### ISSUE TITLE
Does not receive/forward remote packets with Windows as client

### ISSUE THREAD

**Issue by JustinGrote** [SenseUnit/dtlspipe#27]
I've set up `dtlspipe` to listen and can send it syslog messages on the same host, however remote UDP packets fail to arrive. I've verified the windows firewall is completely turned off, and that it is listening on the port, and that wireshark is seeing the syslog packets arrive at the machine.

In this environment I don't have a linux host to work with but the linux host I do have accepts the remote syslog packets fine. I tried it with high ports (10514) as well as admin privileges.

![image](https://github.com/user-attachments/assets/70277902-5c0a-422b-a43d-ec0146c29f72)

## Sending syslog from remote host (.53) to local one (.52), it does arrive according to wireshark
![image](https://github.com/user-attachments/assets/c7963533-ec7f-4a2b-aed0-73efd005c94d)

Note it does not show up in the above log, but the local send does.

Verified it is listening on port 514 (I also tried 10514 in case windows high port rules were being enforced)
![image](https://github.com/user-attachments/assets/70277902-5c0a-422b-a43d-ec0146c29f72)

**Comment by Snawoot** [comment]
Hello!

If client log indicates "connection" was accepted and there is no timeout/handshake errors, then we can be sure UDP gets forwarded to DTLS pipe and to DTLS server.

Check server logs to confirm "connection" was accepted and forwarding took place. Then check if UDP datagrams come out of DTLS pipe server. It's possible UDP datagrams coming out of dtlspipe server, but not getting accepted by remote (wrong address, mismatching bind address and so on).

For clarity, please attach dtlspipe server logs.

**Comment by JustinGrote** [comment]
Thanks @Snawoot, I see all the connection working if I send a syslog from the local server to its outside address using a PowerShell script, however the syslogs arriving remotely do not trigger a connection. I've also verified this doesn't happen on Linux but for my use case it has to be Windows unfortunately. I'm wondering if this is a Golang windows limitation or something special that has to be added to the listener for it to accept remote connections.

Steps to reproduce:
1. Linux dtlspipe server
2. Windows dtlspipe client
3. Additional remote syslog sender (can be in same subnet as windows dtlspipe client)
4. Configure DTLSpipe client and server using either 0.0.0.0 or specific public IP address for listeners
5. Confirm port is listening via netstat
6. Send syslog test from the windows dtlspipe client to itself on its listening port (this should work)
7. Send syslog from remote syslog sender to windows dtlspipe client. This never gets picked up by the listener.
8. Verify the packet is arriving via wireshark and that windows firewall is disabled.

I will get an Azure lab together to reproduce and can provide access to help facilitate troubleshooting. I have some basic familiarity with Go so I can also try to step the code via vscode.

**Comment by Snawoot** [comment]
> I will get an Azure lab together to reproduce and can provide access to help facilitate troubleshooting.

Nice, let's do it!

But also logs from current setup will be useful.

**Comment by JustinGrote** [comment]
Not sure if there is a debug logging parameter, but the regular logging on the server is nothing new, and the logs are only showing for the syslogs I initiate locally. The logs I initate remotely don't even trigger a client connection log entry


## Server Log
```
DTLSPIPE: 2024/07/17 00:05:21.844089 main.go:234: starting dtlspipe client: 10.0.0.4:20514 =[wrap into DTLS]=> 10.0.0.4:10514
DTLSPIPE: 2024/07/17 00:05:30.356412 client.go:108: [+] conn 10.0.0.4:20514 <=> 73.25.61.31:50061
DTLSPIPE: 2024/07/17 00:05:31.623814 client.go:108: [+] conn 10.0.0.4:20514 <=> 73.25.61.31:50062
DTLSPIPE: 2024/07/17 00:05:32.270111 client.go:108: [+] conn 10.0.0.4:20514 <=> 73.25.61.31:54731
DTLSPIPE: 2024/07/17 00:06:00.369519 util.go:96: dropping stale connection 10.0.0.4:60485 <=> 10.0.0.4:10514
DTLSPIPE: 2024/07/17 00:06:00.369517 util.go:96: dropping stale connection 10.0.0.4:20514 <=> 73.25.61.31:50061
DTLSPIPE: 2024/07/17 00:06:00.369771 client.go:136: [-] conn 10.0.0.4:20514 <=> 73.25.61.31:50061
DTLSPIPE: 2024/07/17 00:06:01.626113 util.go:96: dropping stale connection 10.0.0.4:36458 <=> 10.0.0.4:10514
DTLSPIPE: 2024/07/17 00:06:01.626178 util.go:104: read from 73.25.61.31:50062 error: EOF
DTLSPIPE: 2024/07/17 00:06:01.626278 client.go:136: [-] conn 10.0.0.4:20514 <=> 73.25.61.31:50062
DTLSPIPE: 2024/07/17 00:06:02.271822 util.go:96: dropping stale connection 10.0.0.4:58566 <=> 10.0.0.4:10514
DTLSPIPE: 2024/07/17 00:06:02.272144 util.go:104: read from 73.25.61.31:54731 error: EOF
DTLSPIPE: 2024/07/17 00:06:02.272300 client.go:136: [-] conn 10.0.0.4:20514 <=> 73.25.61.31:54731
DTLSPIPE: 2024/07/17 00:06:06.816236 client.go:108: [+] conn 10.0.0.4:20514 <=> 73.25.61.31:56380
DTLSPIPE: 2024/07/17 00:06:10.561481 client.go:108: [+] conn 10.0.0.4:20514 <=> 73.25.61.31:56381
DTLSPIPE: 2024/07/17 00:06:36.818734 util.go:96: dropping stale connection 10.0.0.4:33633 <=> 10.0.0.4:10514
DTLSPIPE: 2024/07/17 00:06:36.818745 util.go:96: dropping stale connection 10.0.0.4:20514 <=> 73.25.61.31:56380
DTLSPIPE: 2024/07/17 00:06:36.819044 client.go:136: [-] conn 10.0.0.4:20514 <=> 73.25.61.31:56380
DTLSPIPE: 2024/07/17 00:06:40.568029 util.go:96: dropping stale connection 10.0.0.4:57931 <=> 10.0.0.4:10514
DTLSPIPE: 2024/07/17 00:06:40.568059 util.go:104: read from 73.25.61.31:56381 error: EOF
DTLSPIPE: 2024/07/17 00:06:40.568213 client.go:136: [-] conn 10.0.0.4:20514 <=> 73.25.61.31:56381
Connection to socsyslog-t.westus2.cloudapp.azure.com closed by remote host.
```

**Comment by JustinGrote** [comment]
OK, in the lab at least on a 2022 machine, I am able to get remote syslogs to reach the windows host, so at least it's possible, I'll investigate what's wrong with my setup and reopen if I can find a more specific issue. Thanks!

**Comment by JustinGrote** [comment]
@Snawoot to close the loop on this, in the environment where I was running this, someone had configured local group policy to force the win firewall on. Even though it was disabled and showed as "off" via `netsh advfirewall`. Removing the local GPO and things look to be working as expected again. That was maddening. Thanks for your assistance and sorry to spend your time!
