### ISSUE TITLE
Not working, how to debug?

### ISSUE THREAD

**Issue by cornzzy** [SenseUnit/dtlspipe#32]
I have the following setup:

`wireguard client` -> `server1` -> `server2`

wireguard client is simply using wireguard pointing to server1:3535

server1 is running `dtlspipe -psk xx client 127.0.0.1:3535 server2:443`

server2 is running wireguard listening on 2525 and running `dtlspipe -psk xx server 0.0.0.0:443 127.0.0.1:2525`

No traffic happens when wg client connects and mtu is 1280. The same routing works with udp2raw. How do I find the issue?

**Comment by Snawoot** [comment]
Hello!

If wireguard client and server1 is not the same machine, then bind address of dtlspipe client is incorrect: you should use wildcard bind address 0.0.0.0 instead of 127.0.0.1.

**Comment by cornzzy** [comment]
you de best
