### ISSUE TITLE
remote dial failed: DTLS handshake with remote server failed: handshake

### ISSUE THREAD

**Issue by ssrsec** [SenseUnit/dtlspipe#35]
DTLSPIPE: 2024/09/14 23:40:42.345137 client.go:111: [+] conn 127.0.0.1:61524 <=> 127.0.0.1:50344
DTLSPIPE: 2024/09/14 23:40:42.346150 client.go:146: remote dial failed: DTLS handshake with remote server failed: handshake error: write udp [::]:55703->154.91.183.22:61525: sendto: no route to host
DTLSPIPE: 2024/09/14 23:40:42.346188 client.go:147: [-] conn 127.0.0.1:61524 <=> 127.0.0.1:50344
DTLSPIPE: 2024/09/14 23:40:47.387398 client.go:111: [+] conn 127.0.0.1:61524 <=> 127.0.0.1:50344

**Comment by Snawoot** [comment]
> 154.91.183.22:61525: sendto: no route to host

Looks like a firewall issue to me. Please check if firewall on server doesn't block UDP port 61525 and your firewall on your local system doesn't do that as well.

**Comment by ssrsec** [comment]
Neither the server nor my local system has a firewall turned on.

**Comment by Snawoot** [comment]
Which OS you are using  on client?

**Comment by ssrsec** [comment]
macos
